"""
Boolean Search Router — SRP SmartRecruit v4.0
Generate recruiter-ready boolean search strings from JD or skill input
"""

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from typing import List, Optional

from app.database.connection import get_db
from app.auth.dependencies import get_current_verified_user
from app.models.user import User
from app.services.boolean_search_service import BooleanSearchService

router = APIRouter(prefix="/api/v4/boolean-search", tags=["Boolean Search"])


# ─────────────────────────────────────────────────────────────────────────────
# Schemas
# ─────────────────────────────────────────────────────────────────────────────

class BooleanSearchRequest(BaseModel):
    job_title:    str = Field(..., min_length=2, max_length=200)
    skills:       List[str] = Field(default_factory=list)
    experience:   Optional[str] = None
    location:     Optional[str] = None
    jd_text:      Optional[str] = Field(None, max_length=20000)
    source_jd_id: Optional[int] = None


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/generate", status_code=status.HTTP_201_CREATED)
async def generate_boolean_search(
    request: BooleanSearchRequest,
    current_user: User = Depends(get_current_verified_user),
    db: Session = Depends(get_db),
):
    """
    Generate LinkedIn, Naukri, and Indeed compatible boolean search strings.

    Accepts either:
    - job_title + skills (quick mode)
    - jd_text (full JD parsing mode — more accurate)

    Returns:
    - short_boolean: compact recruiter string
    - advanced_boolean: full AND/OR/NOT logic version
    - alternate_boolean: synonym / alternate title variant
    - linkedin_search, naukri_search, indeed_search: platform-optimized
    - must_have / nice_to_have / exclude keyword lists
    """
    try:
        params = request.model_dump(exclude_none=True)
        record = BooleanSearchService.generate(db, current_user, params)
        return {
            "id":               record.id,
            "job_title":        record.job_title,
            "must_have":        record.must_have,
            "nice_to_have":     record.nice_to_have,
            "exclude_keywords": record.exclude_keywords,
            "short_boolean":    record.short_boolean,
            "advanced_boolean": record.advanced_boolean,
            "alternate_boolean": record.alternate_boolean,
            "linkedin_search":  record.linkedin_search,
            "naukri_search":    record.naukri_search,
            "indeed_search":    record.indeed_search,
            "created_at":       record.created_at.isoformat(),
        }
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Boolean search generation failed: {str(e)}")


@router.get("/list")
async def list_boolean_searches(
    current_user: User = Depends(get_current_verified_user),
    db: Session = Depends(get_db),
    limit: int = 20,
):
    """List all boolean searches generated by the current user."""
    records = BooleanSearchService.list(db, current_user, limit=min(limit, 50))
    return {
        "searches": [
            {
                "id":            r.id,
                "job_title":     r.job_title,
                "short_boolean": r.short_boolean,
                "created_at":    r.created_at.isoformat(),
            }
            for r in records
        ]
    }


@router.get("/{search_id}")
async def get_boolean_search(
    search_id: int,
    current_user: User = Depends(get_current_verified_user),
    db: Session = Depends(get_db),
):
    """Get a specific boolean search result by ID."""
    record = BooleanSearchService.get(db, current_user, search_id)
    if not record:
        raise HTTPException(status_code=404, detail="Boolean search not found")
    return {
        "id":               record.id,
        "job_title":        record.job_title,
        "must_have":        record.must_have,
        "nice_to_have":     record.nice_to_have,
        "exclude_keywords": record.exclude_keywords,
        "short_boolean":    record.short_boolean,
        "advanced_boolean": record.advanced_boolean,
        "alternate_boolean": record.alternate_boolean,
        "linkedin_search":  record.linkedin_search,
        "naukri_search":    record.naukri_search,
        "indeed_search":    record.indeed_search,
        "input_text":       record.input_text,
        "created_at":       record.created_at.isoformat(),
    }
